from enum import Enum


class EventType(str, Enum):
    DEVICE_CREATED = "DEVICE_CREATED"
    DEVICE_UPDATED = "DEVICE_UPDATED"
    POWER_READING = "POWER_READING"
    DEVICE_COMMAND = "DEVICE_COMMAND"
    UPDATE_REQUEST = "UPDATE_REQUEST"
    
