"""auto migration

Revision ID: 0b325ebab07d
Revises: eb1c576d4b7b
Create Date: 2025-11-08 12:05:08.897242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b325ebab07d'
down_revision: Union[str, Sequence[str], None] = 'eb1c576d4b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inverters', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inverters', 'created_at')
    # ### end Alembic commands ###
