"""auto migration

Revision ID: 467c6c66e005
Revises: 9fea989c7e5a
Create Date: 2025-11-23 12:21:10.567091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467c6c66e005'
down_revision: Union[str, Sequence[str], None] = '9fea989c7e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_number', sa.Integer(), nullable=False))
    op.drop_column('devices', 'gpio_pin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('gpio_pin', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('devices', 'device_number')
    # ### end Alembic commands ###
