"""auto migration

Revision ID: 5188f3a6e854
Revises: 25196f8349bd
Create Date: 2025-11-11 13:54:52.267846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5188f3a6e854'
down_revision: Union[str, Sequence[str], None] = '25196f8349bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('devices_uuid_key'), 'devices', type_='unique')
    op.create_index(op.f('ix_devices_uuid'), 'devices', ['uuid'], unique=True)
    op.add_column('raspberries', sa.Column('secret_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raspberries', 'secret_key')
    op.drop_index(op.f('ix_devices_uuid'), table_name='devices')
    op.create_unique_constraint(op.f('devices_uuid_key'), 'devices', ['uuid'], postgresql_nulls_not_distinct=False)
    op.alter_column('devices', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
