"""auto migration

Revision ID: 6385f226187d
Revises: 703f7de1b69d
Create Date: 2025-11-10 13:21:21.122219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6385f226187d'
down_revision: Union[str, Sequence[str], None] = '703f7de1b69d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('schedule', sa.JSON(), nullable=True))
    op.alter_column('devices', 'gpio_pin',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('devices', 'mode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('devices', 'last_update',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'last_update',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('devices', 'mode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('devices', 'gpio_pin',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('devices', 'schedule')
    # ### end Alembic commands ###
