"""auto migration

Revision ID: 703f7de1b69d
Revises: a152b0c41a58
Create Date: 2025-11-10 11:10:51.382277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703f7de1b69d'
down_revision: Union[str, Sequence[str], None] = 'a152b0c41a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raspberries', sa.Column('max_devices', sa.Integer(), nullable=True))
    op.add_column('raspberries', sa.Column('gpio_pins', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raspberries', 'gpio_pins')
    op.drop_column('raspberries', 'max_devices')
    # ### end Alembic commands ###
