"""auto migration

Revision ID: a152b0c41a58
Revises: ddb1964b457c
Create Date: 2025-11-10 10:58:34.840595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a152b0c41a58'
down_revision: Union[str, Sequence[str], None] = 'ddb1964b457c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raspberries', sa.Column('uuid', sa.UUID(), nullable=True))
    op.add_column('raspberries', sa.Column('inverter_id', sa.Integer(), nullable=True))
    op.add_column('raspberries', sa.Column('firmware_version', sa.String(), nullable=True))
    op.add_column('raspberries', sa.Column('system_info', sa.JSON(), nullable=True))
    op.add_column('raspberries', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('raspberries', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('raspberries_identifier_key'), 'raspberries', type_='unique')
    op.create_index(op.f('ix_raspberries_uuid'), 'raspberries', ['uuid'], unique=True)
    op.drop_constraint(op.f('raspberries_user_id_fkey'), 'raspberries', type_='foreignkey')
    op.create_foreign_key(None, 'raspberries', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'raspberries', 'inverters', ['inverter_id'], ['id'], ondelete='SET NULL')
    op.drop_column('raspberries', 'identifier')
    op.drop_column('raspberries', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raspberries', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('raspberries', sa.Column('identifier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'raspberries', type_='foreignkey')
    op.drop_constraint(None, 'raspberries', type_='foreignkey')
    op.create_foreign_key(op.f('raspberries_user_id_fkey'), 'raspberries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_raspberries_uuid'), table_name='raspberries')
    op.create_unique_constraint(op.f('raspberries_identifier_key'), 'raspberries', ['identifier'], postgresql_nulls_not_distinct=False)
    op.alter_column('raspberries', 'last_seen',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('raspberries', 'description')
    op.drop_column('raspberries', 'system_info')
    op.drop_column('raspberries', 'firmware_version')
    op.drop_column('raspberries', 'inverter_id')
    op.drop_column('raspberries', 'uuid')
    # ### end Alembic commands ###
