"""auto migration

Revision ID: d12d5ef8092f
Revises: 7378582017d1
Create Date: 2025-11-11 13:12:15.607068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12d5ef8092f'
down_revision: Union[str, Sequence[str], None] = '7378582017d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('uuid', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'devices', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_column('devices', 'uuid')
    # ### end Alembic commands ###
