"""auto migration

Revision ID: eb1c576d4b7b
Revises: c01b8eea4993
Create Date: 2025-11-08 11:56:42.967813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb1c576d4b7b'
down_revision: Union[str, Sequence[str], None] = 'c01b8eea4993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inverters', sa.Column('dev_type_id', sa.Integer(), nullable=True))
    op.add_column('inverters', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('inverters', sa.Column('longitude', sa.Float(), nullable=True))
    op.alter_column('inverters', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inverters', 'last_updated',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('inverters', 'longitude')
    op.drop_column('inverters', 'latitude')
    op.drop_column('inverters', 'dev_type_id')
    # ### end Alembic commands ###
